// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCsIQsxR0Jm164_dE4Ki-v9x3HKikQCl38',
    appId: '1:911976925555:web:24bd869b729b52f944dd06',
    messagingSenderId: '911976925555',
    projectId: 'task-app-99ee0',
    authDomain: 'task-app-99ee0.firebaseapp.com',
    storageBucket: 'task-app-99ee0.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCLcjAtmcDlkPBbVCCK7JfVm7t3mVw8W0o',
    appId: '1:911976925555:android:7055ddbea87a2fe344dd06',
    messagingSenderId: '911976925555',
    projectId: 'task-app-99ee0',
    storageBucket: 'task-app-99ee0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAOUiy_-wEooP6eSBPbBKQvaFXjolQR8dk',
    appId: '1:911976925555:ios:7b32adae4e1ed54244dd06',
    messagingSenderId: '911976925555',
    projectId: 'task-app-99ee0',
    storageBucket: 'task-app-99ee0.appspot.com',
    iosBundleId: 'com.example.taskk',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCsIQsxR0Jm164_dE4Ki-v9x3HKikQCl38',
    appId: '1:911976925555:web:f506f2b63b7e46f844dd06',
    messagingSenderId: '911976925555',
    projectId: 'task-app-99ee0',
    authDomain: 'task-app-99ee0.firebaseapp.com',
    storageBucket: 'task-app-99ee0.appspot.com',
  );

}